apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kener.fullname" . }}-config
data:
  site.yaml: |
    {{- toYaml .Values.site | nindent 4 }}
  monitors.yaml: |
    {{- toYaml .Values.monitors | nindent 4 }}
  server.yaml: |
    {{- toYaml .Values.server | nindent 4 }}